stages:
  - test
  - release

black:
  image: python:3.6-alpine
  stage: test
  script:
    - apk add -U gcc musl-dev
    - pip install -r requirements-dev.txt
    - black --check pyzwave tests

pylint:
  image: python:3.6-alpine
  stage: test
  script:
    - apk add -U git gcc musl-dev
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pylint --rcfile=.pylintrc $(git ls-tree --name-only --full-tree -r HEAD | grep '\.py$' | sort | tr '\n' ' ') || RETCODE=1

unittest:
  image: python:3.6-alpine
  stage: test
  coverage: '/^TOTAL.+?(\d+\%)$/'
  variables:
    CI_BRANCH: "${CI_COMMIT_REF_NAME}"
  script:
    - apk add -U gcc git musl-dev
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - python -m pytest --cov=pyzwave --cov-report term-missing
    - coveralls

pypi:
  image: python:3.6-alpine
  stage: release
  only:
    - tags
  environment:
    name: pypi
    url: https://pypi.org/project/python-zwave/
  when: manual
  script:
    - cp ${PYPIRC} ~/.pypirc
    - apk add -U gcc musl-dev libffi-dev openssl-dev
    - pip install twine setuptools wheel
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
